const Joi = require('joi');

const propertySchema = Joi.object({
    Titile: Joi.string().required(),
    Description: Joi.string().required(),
    Highlight: Joi.string().required(),
    ProeprtyFor: Joi.string().valid('Rent', 'Sale', 'Lease').required(),
    ProjectId: Joi.string().pattern(/^[0-9a-fA-F]{24}$/),
    PropertyTypeWithSubtype: Joi.array().items(Joi.string()),
    IsDeleted: Joi.boolean(),
    IsEnabled: Joi.boolean(),
    IsExclusive: Joi.boolean(),
    IsFeatured: Joi.boolean(),
    IsNew: Joi.boolean(),
    Features: Joi.array().items(Joi.string()),
    Aminities: Joi.array().items(Joi.string()),
    Facing: Joi.array().items(Joi.string()),
    City: Joi.string(),
    State: Joi.string(),
    Country: Joi.string(),
    Address: Joi.string(),
    Landmark: Joi.string(),
    PinCode: Joi.string(),
    Location: Joi.object({
        Latitude: Joi.number(),
        Longitude: Joi.number()
    }),
    CreatedDate: Joi.date(),
    CreatedBy: Joi.string(),
    UpdatedDate: Joi.date(),
    UpdatedBy: Joi.string(),
    Bedrooms: Joi.number().integer().min(0),
    Bathrooms: Joi.number().integer().min(0),
    Fencing: Joi.string(),
    Flooring: Joi.string(),
    Furnished: Joi.string(),
    BuiltAreaType: Joi.string(),
    LandArea: Joi.number().min(0),
    CoveredArea: Joi.number().min(0),
    CarpetArea: Joi.number().min(0),
    TotalPrice: Joi.number().min(0),
    PerUnitPrice: Joi.number().min(0),
    IsDisplayPrice: Joi.boolean(),
    IsNegotiable: Joi.boolean(),
    PosessionStatus: Joi.string(),
    PosessionDate: Joi.date(),
    FloorNumber: Joi.number().integer().min(0),
    TotalFloors: Joi.number().integer().min(0),
    IsSingleProperty: Joi.boolean(),
    PricePerSquareFeet: Joi.number().min(0),
    FloorsAllowed: Joi.number().integer().min(0),
    IsInterstedInJoinedVenture: Joi.boolean(),
    Balconies: Joi.number().integer().min(0),
    ApprovedBy: Joi.array().items(Joi.string()),
    ReraNumber: Joi.string(),
    Soil: Joi.string(),
    IsLoanable: Joi.boolean(),
    IsAlreadyLoaned: Joi.boolean(),
    LoanDetails: Joi.object({
        ByBank: Joi.string(),
        LoanSince: Joi.date(),
        LoanTill: Joi.date()
    }),
    OwnershipType: Joi.string(),
    PropertyStatus: Joi.string(),
    Images: Joi.array().items(Joi.object({
        Name: Joi.string(),
        Titile: Joi.string(),
        URL: Joi.string(),
        Type: Joi.string(),
        IsDeleted: Joi.boolean(),
        IsEnabled: Joi.boolean()
    })),
    Documents: Joi.array().items(Joi.object({
        Name: Joi.string(),
        Titile: Joi.string(),
        URL: Joi.string(),
        Type: Joi.string(),
        IsDeleted: Joi.boolean(),
        IsEnabled: Joi.boolean()
    })),
    Videos: Joi.array().items(Joi.object({
        Name: Joi.string(),
        Titile: Joi.string(),
        URL: Joi.string(),
        Type: Joi.string(),
        IsDeleted: Joi.boolean(),
        IsEnabled: Joi.boolean()
    })),
    IsSold: Joi.boolean(),
    PurchaseRentBy: Joi.object({
        BuyerId: Joi.string().pattern(/^[0-9a-fA-F]{24}$/),
        PurchaseDate: Joi.date(),
        PurchaseAmount: Joi.number().min(0),
        RegistryNumber: Joi.string(),
        TenantId: Joi.string().pattern(/^[0-9a-fA-F]{24}$/),
        RentAmount: Joi.number().min(0),
        RentStartDate: Joi.date(),
        RentEndDate: Joi.date(),
        RenewedOn: Joi.date(),
        SellerId: Joi.string().pattern(/^[0-9a-fA-F]{24}$/),
        Documents: Joi.array().items(Joi.string())
    }),
    Preferences: Joi.array().items(Joi.string()),
    DiscountPercentage: Joi.number().min(0),
    DiscountForYears: Joi.number().min(0),
    Surveillance: Joi.array().items(Joi.string())
});

module.exports = propertySchema;
